### ISSUE TITLE
Mustache.js v0.4.0 ?

### ISSUE THREAD

**Issue by rafi** [HenrikJoreteg/ICanHaz.js#40]
Mustache.js v0.4.0 is out... any plans on upgrading?

**Comment by dtipson** [comment]
Also, can Mustache.js be exposed as its own function, since it's included anyhow, so that people can use it for non-ich templating (say, a simple template in a js library)?  I've basically just mapped the bundled version to a global variable to make this work for me, but I'm not 100% sure if that's the right approach for the library itself.

**Comment by HenrikJoreteg** [comment]
It's updated and there's now a version available ICanHaz-no-mustache.js that doesn't bundle, it just expects a `Mustache` global. Then you can include whatever version of mustache you want separately, which also means you can optionally expose it as a global.
